SCREEN_W = 128
SCREEN_H = 128
FPS = 30
TITLE = "GEVISE75"

FIELD_OFFSET_X = 4
FIELD_OFFSET_Y = 10
FIELD_W = 120
FIELD_H = 106

ENERGY_ZONE_H = 8  # 画面上部エネルギーゲージエリア高さ

HUD_Y = 118
HUD_H = 10

# Pyxel 標準パレット色番号
COL_BLACK = 0
COL_NAVY = 1
COL_PURPLE = 2
COL_GREEN = 3
COL_BROWN = 4
COL_DARK_GREY = 5
COL_LIGHT_GREY = 6
COL_WHITE = 7
COL_RED = 8
COL_ORANGE = 9
COL_YELLOW = 10
COL_LIME = 11
COL_BLUE = 12
COL_INDIGO = 13
COL_PINK = 14
COL_PEACH = 15

# ゲームルール定数
CLEAR_RATIO = 0.75
INITIAL_CRAWLERS = 2
# エネルギーシステム
ENERGY_MAX = 100.0
ENERGY_DECAY = 1.0 / 30  # 1フレームあたりの減少量 (1秒で1消費)
ENERGY_MISS_PENALTY = 25.0  # 衝突ペナルティ
ENERGY_CLEAR_BONUS = 15.0  # ステージクリアボーナス
ENERGY_TRAIL_K = 0.03  # Trail長回復係数 (gain = K * trail_length^N)
ENERGY_TRAIL_N = 1.5  # Trail長回復指数
ENERGY_DECAY_STAGE_SCALE = 0.2
ENERGY_DECAY_DRAWING_MULT = 2.0

# ステージスケーリング定数
DRIFT_SPEED_BASE = 1.5
DRIFT_SPEED_STAGE_INC = 0.15
DRIFT_SPEED_MAX = 2.2
DRIFT_COUNT_STAGE_INTERVAL = 3
DRIFT_COUNT_MAX = 3
CRAWLER_INTERVAL_MIN_BASE = 6
CRAWLER_INTERVAL_MAX_BASE = 8
CRAWLER_INTERVAL_MIN_FLOOR = 2
CRAWLER_INTERVAL_MAX_FLOOR = 3

# UI定数
CHAR_W = 4  # Pyxel組み込みフォントの文字幅(px)
